CREATE TABLE ChatDB.Admins
(Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
Username VARCHAR(256) NOT NULL UNIQUE,
Passhash VARCHAR(256) NOT NULL,
Email VARCHAR(256) NOT NULL UNIQUE,
Created BIGINT NOT NULL);

CREATE TABLE ChatDB.Users
(Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
OwnerId INT,
Username VARCHAR(256) NOT NULL UNIQUE,
Passhash VARCHAR(256),
Uuid VARCHAR(256),
Email VARCHAR(256),
Created BIGINT NOT NULL,
Destroyed BIGINT,
CONSTRAINT OwnerFK FOREIGN KEY (OwnerId) REFERENCES ChatDB.Users (Id) ON DELETE CASCADE);

CREATE TABLE ChatDB.Events
(Id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
TimeStampx BIGINT NOT NULL,
Typex VARCHAR(64) NOT NULL,
SourceId INT NOT NULL,
TargetId INT,
RoomName VARCHAR(256),
Message VARCHAR(2400),
CONSTRAINT SourceFK FOREIGN KEY (SourceId) REFERENCES ChatDB.Users (Id) ON DELETE RESTRICT,
CONSTRAINT TargetFK FOREIGN KEY (TargetId) REFERENCES ChatDB.Users (Id) ON DELETE RESTRICT);