CREATE DATABASE IF NOT EXISTS ChatDB
DEFAULT CHARACTER SET = 'Utf8';

USE ChatDB;

CREATE USER rooot IDENTIFIED BY 'root'; 

GRANT USAGE ON *.* to rooot@localhost IDENTIFIED BY 'root'; 
GRANT ALL PRIVILEGES ON ChatDB.* TO rooot@localhost; 

CREATE TABLE IF NOT EXISTS ChatDB.Admins
(Id INT PRIMARY KEY AUTO_INCREMENT,
Username VARCHAR(256) NOT NULL UNIQUE,
Passhash VARCHAR(256) NOT NULL,
Email VARCHAR(256) NOT NULL UNIQUE,
Created BIGINT(64) NOT NULL,
INDEX (Username));

CREATE TABLE IF NOT EXISTS ChatDB.Users
(Id INT PRIMARY KEY AUTO_INCREMENT,
OwnerId INT,
Username VARCHAR(256) NOT NULL UNIQUE,
Passhash VARCHAR(256) NULL,
Uuid VARCHAR(256) NULL,
Email VARCHAR(256) NULL,
Created BIGINT(64) NOT NULL,
Destroyed BIGINT(64) NULL,
INDEX (Username),
CONSTRAINT FOREIGN KEY (OwnerId) 
	REFERENCES ChatDB.Users (Id) 
    ON DELETE CASCADE);
    
CREATE TABLE IF NOT EXISTS ChatDB.Events
(Id INT PRIMARY KEY AUTO_INCREMENT,
TimeStampx BIGINT(64) NOT NULL,
Typex VARCHAR(64) NOT NULL,
SourceId INT NOT NULL,
TargetId INT,
RoomName VARCHAR(256),
Message VARCHAR(2400),
INDEX (SourceId),
CONSTRAINT FOREIGN KEY (SourceId)
	REFERENCES ChatDB.Users (Id)
    ON DELETE RESTRICT,
CONSTRAINT FOREIGN KEY (TargetId)
	REFERENCES ChatDB.Users (Id)
    ON DELETE RESTRICT);
 

